# Generated by Django 2.2.22 on 2023-03-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_quality', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_rank', to='image_quality.Rank'),
        ),
    ]
