# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Annotation', '0007_keyframe_image'),
        ('Segmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Annotation.Image')),
            ],
        ),
        migrations.CreateModel(
            name='BoundingBoxTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset', models.ManyToManyField(to='Annotation.Dataset')),
                ('label', models.ManyToManyField(to='Segmentation.SegmentationLabel')),
            ],
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoundingBox.BoundingBoxTask'),
        ),
    ]
