# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0007_keyframe_image'),
        ('BoundingBox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Annotation.Image')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoundingBox.BoundingBoxTask')),
            ],
        ),
        migrations.RemoveField(
            model_name='boundingbox',
            name='date',
        ),
        migrations.RemoveField(
            model_name='boundingbox',
            name='task',
        ),
        migrations.AlterField(
            model_name='boundingbox',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoundingBox.CompletedImage'),
        ),
    ]
