# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundingbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='completedimage',
            name='task',
        ),
        migrations.AlterField(
            model_name='boundingbox',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ProcessedImage'),
        ),
        migrations.DeleteModel(
            name='CompletedImage',
        ),
    ]
