# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Segmentation', '0001_initial'),
        ('BoundingBox', '0002_auto_20160905_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='boundingbox',
            name='label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Segmentation.SegmentationLabel'),
            preserve_default=False,
        ),
    ]
