# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Annotation', '0007_keyframe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color_red', models.PositiveSmallIntegerField()),
                ('color_green', models.PositiveSmallIntegerField()),
                ('color_blue', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SegmentationTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dataset', models.ManyToManyField(to='Annotation.Dataset')),
                ('label', models.ManyToManyField(to='Segmentation.SegmentationLabel')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Annotation.Image')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Segmentation.SegmentationTask')),
            ],
        ),
    ]
