# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotationweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Image')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Label')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Task')),
            ],
        ),
    ]
