# Generated by Django 2.2.1 on 2020-01-14 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelabel',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.KeyFrameAnnotation'),
        ),
    ]
