# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0004_processedimage'),
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ProcessedImage')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Label')),
            ],
        ),
        migrations.RemoveField(
            model_name='classifiedimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='classifiedimage',
            name='label',
        ),
        migrations.RemoveField(
            model_name='classifiedimage',
            name='task',
        ),
        migrations.DeleteModel(
            name='ClassifiedImage',
        ),
    ]
