# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-10 06:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation_polygon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentationpolygon',
            old_name='frames',
            new_name='target_frames',
        ),
    ]
