# Generated by Django 2.2.24 on 2022-06-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0008_auto_20220602_1428'),
        ('spline_line_point', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ControlPoint',
            new_name='ControlPoint_splineLinePoint',
        ),
    ]
