# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotationweb', '0015_auto_20170719_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('index', models.PositiveIntegerField()),
                ('phase', models.PositiveIntegerField(choices=[(0, 'End Diastole'), (1, 'End Systole')])),
                ('object', models.PositiveIntegerField(choices=[(0, 'Endocardium'), (1, 'Epicardium'), (2, 'Left atrium')])),
            ],
        ),
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_ED', models.PositiveIntegerField()),
                ('frame_ES', models.PositiveIntegerField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ProcessedImage')),
            ],
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='segmentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardiac.Segmentation'),
        ),
    ]
