# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentation',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ProcessedImage'),
        ),
    ]
