# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0002_auto_20170719_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='motion_mode_line',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
