# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0003_segmentation_motion_mode_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlpoint',
            name='uncertain',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
