# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardiac', '0004_controlpoint_uncertain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentation',
            name='frame_ED',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='frame_ES',
            field=models.IntegerField(),
        ),
    ]
