# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0002_labeledimage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dataset',
        ),
        migrations.AddField(
            model_name='task',
            name='dataset',
            field=models.ManyToManyField(to='Annotation.Dataset'),
        ),
    ]
