# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Annotation', '0006_imagesequence_nr_of_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='image',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='Annotation.Image'),
            preserve_default=False,
        ),
    ]
