# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=1024)),
                ('nr_of_frames', models.PositiveIntegerField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='KeyFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_nr', models.PositiveIntegerField()),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Image')),
                ('image_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ImageSequence')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color_red', models.PositiveSmallIntegerField()),
                ('color_green', models.PositiveSmallIntegerField()),
                ('color_blue', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('segmentation', 'Segmentation'), ('boundingbox', 'Bounding box')], max_length=50)),
                ('dataset', models.ManyToManyField(to='annotationweb.Dataset')),
                ('label', models.ManyToManyField(to='annotationweb.Label')),
            ],
        ),
    ]
