# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-05-13 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='image',
            new_name='keyframe',
        ),
    ]
