# Generated by Django 2.2.1 on 2019-11-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0002_auto_20191118_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframeannotation',
            name='frame_metadata',
            field=models.CharField(default='', help_text='A text field for storing arbitrary metadata on the current frame', max_length=512),
        ),
    ]
