# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0002_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='frames_after',
            field=models.PositiveIntegerField(default=0, help_text='How many frames to allow user to see after a key frame'),
        ),
        migrations.AddField(
            model_name='task',
            name='frames_before',
            field=models.PositiveIntegerField(default=0, help_text='How many frames to allow user to see before a key frame'),
        ),
        migrations.AddField(
            model_name='task',
            name='show_entire_sequence',
            field=models.BooleanField(default=False, help_text='Allow user to see entire sequence.'),
        ),
    ]
