# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-05-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0002_auto_20190513_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyframe',
            name='task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Task'),
            preserve_default=False,
        ),
    ]
