# Generated by Django 2.2.1 on 2020-11-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0003_keyframeannotation_frame_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageannotation',
            name='finished',
            field=models.BooleanField(default=True),
        ),
    ]
