# Generated by Django 2.2.1 on 2019-11-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0002_auto_20191111_1840'),
        ('annotationweb', '0003_keyframeannotation_frame_metadata'),
    ]

    operations = [
    ]
