# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0006_auto_20161024_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='auto_play',
            field=models.BooleanField(default=True, help_text='Auto play image sequences'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
