# Generated by Django 4.2.27 on 2025-12-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0007_auto_20230202_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['dataset__name', 'name']},
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('boundingbox', 'Bounding Box'), ('landmark', 'Landmark'), ('cardiac', 'Cardiac Apical 2CH/4CH Segmentation'), ('spline_segmentation', 'Spline Segmentation'), ('spline_line_point', 'Spline, Line and Point'), ('cardiac_parasternal_long_axis', 'Cardiac Parasternal Long Axis Segmentation'), ('cardiac_apical_long_axis', 'Cardiac Apical Long Axis Segmentation'), ('image_quality', 'Image Quality'), ('caliper', 'Caliper')], max_length=50),
        ),
    ]
