# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-27 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0007_auto_20161027_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='image_quality',
            field=models.CharField(choices=[('poor', 'Poor'), ('ok', 'OK'), ('good', 'Good')], default='ok', max_length=50),
            preserve_default=False,
        ),
    ]
