# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0008_processedimage_image_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('segmentation', 'Segmentation'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark')], max_length=50),
        ),
    ]
