# Generated by Django 4.2.27 on 2025-12-10 13:42
"""
Type field should now be the name of the app. This migration fix that
"""

from django.db import migrations

type_value_changes = {
    'cardiac_segmentation': 'cardiac',
    'cardiac_plax_segmentation': 'cardiac_parasternal_long_axis',
    'cardiac_alax_segmentation': 'cardiac_apical_long_axis',
}


def update_task_type_values(apps, schema_editor):
    model = apps.get_model('annotationweb', 'task')
    for old_value, new_value in type_value_changes.items():
        model.objects.filter(type=old_value).update(type=new_value)


def reverse_task_type_values(apps, schema_editor):
    model = apps.get_model('annotationweb', 'task')
    for old_value, new_value in type_value_changes.items():
        model.objects.filter(type=new_value).update(type=old_value)


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0008_alter_subject_options_alter_task_type'),
    ]

    operations = [
        migrations.RunPython(
            update_task_type_values,
            reverse_task_type_values
        ),
    ]
