# Generated by Django 5.2.9 on 2025-12-11 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0009_auto_20251210_1442'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageannotation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='show_entire_sequence',
            field=models.BooleanField(default=True, help_text='Allow user to see entire sequence.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_frame_selection',
            field=models.BooleanField(default=True, help_text='Annotaters can select which frames to annotate in a video'),
        ),
    ]
