# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-07 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0009_auto_20161103_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
    ]
