# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-30 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0011_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagesequence',
            name='start_frame_nr',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='imagesequence',
            name='format',
            field=models.CharField(help_text='Should contain # which will be replaced with an integer, increasing with 1 for each frame. E.g. /path/to/frame_#.png', max_length=1024),
        ),
    ]
