# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0011_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='children',
            field=models.ManyToManyField(to='annotationweb.Label'),
        ),
    ]
