# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0012_label_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='children',
        ),
        migrations.AddField(
            model_name='label',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Label'),
        ),
    ]
