# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-16 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0013_auto_20170120_1459'),
        ('annotationweb', '0012_auto_20170130_1349'),
    ]

    operations = [
    ]
