# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-19 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(help_text='<button onclick="window.open(\'/new-label/\', \'Add new label\', \'width=400,height=400,scrollbars=no\');" type="button">Add new label</button>', to='annotationweb.Label'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('segmentation', 'Segmentation'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation')], max_length=50),
        ),
    ]
