# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-04 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0015_auto_20170719_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedimage',
            name='comments',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedimage',
            name='drop',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
