# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0018_auto_20180920_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='large_image_layout',
            field=models.BooleanField(default=False, help_text='Use a large image layout for annotation'),
        ),
    ]
