# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-10-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0018_auto_20180920_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('segmentation', 'Segmentation'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('cardiac_landmark', 'Cardiac landmark'), ('segmentation_polygon', 'Polygon segmentation')], max_length=50),
        ),
    ]
