# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-01-28 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0019_auto_20181008_1854'),
        ('annotationweb', '0019_task_large_image_layout'),
    ]

    operations = [
    ]
