# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2019-04-29 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0022_auto_20190429_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('segmentation', 'Segmentation'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('cardiac_landmark', 'Cardiac landmark'), ('spline_segmentation', 'Spline segmentation')], max_length=50),
        ),
    ]
